branding:
  color: purple
  icon: move
description: 'Move stories on Shortcut.com'
inputs:
  shortcut_story_prefix:
    description: Shortcut prefix (default "sc")
    required: true
    default: 'sc'
  shortcut_review_state_id:
    description: The workflow state where the story should be moved to
    required: true
  shortcut_ready_state_id:
    description: The workflow state where the story should be moved to
    required: true
  shortcut_done_state_id:
    description: The workflow state where the story should not be moved anymore
    required: true
  github_gatekeeper:
    description: GitHub username of the reviewer who manages the workflow state
    required: true
name: Shortcut Move Story With Done Verification
runs:
  main: dist/index.js
  using: node16
